name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      if: github.event.deleted == false
      env:
        DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag ${DOCKER_IMAGE} &&
        docker run ${DOCKER_IMAGE} "https://peaceiris.com" -ro ||
        (echo -e "\e[31m[${GITHUB_WORKFLOW}] failed to build\e[m" && exit 1)
